### ISSUE TITLE
.env file needed when following Local Development Instructions

### ISSUE THREAD

**Issue by mjclemente** [muenzpraeger/eleventy-chirpy-blog-template#43]
# Summary

First, thanks for the fantastic template - it's really awesome, and I'm thrilled that I found it.

The Local Development Instructions are straightforward, but when I followed them, I ran into the following error:

```
[dev:eleventy] Problem writing Eleventy templates: (more in DEBUG output)
[dev:eleventy] > Having trouble rendering njk template ./content/utils/rss.njk
[dev:eleventy] 
[dev:eleventy] `TemplateContentRenderError` was thrown
[dev:eleventy] > (./content/utils/rss.njk)
[dev:eleventy]   TypeError: Invalid URL: /blog.rss
[dev:eleventy] 
[dev:eleventy] `Template render error` was thrown:
[dev:eleventy]     Template render error: (./content/utils/rss.njk)
[dev:eleventy]       TypeError: Invalid URL: /blog.rss
```

I think it's because the environment variables in the `siteconfig.js` are expected. Just wanted to let you know.

## Steps To Reproduce:

Clone the repo and follow the Local Development Instructions.

## Expected result

The website to be served locally.

## Actual result

An error is thrown, as mentioned above.

## Additional information

Happy to add a PR with an `env.example` file and update the instructions accordingly if you'd like. Simply adding the following `.env` file resolved the issue for me:

```
URL=http://localhost
ALGOLIA_APP_ID=
ALGOLIA_SEARCH_API_KEY=
ALGOLIA_SITE_ID=
```

**Comment by muenzpraeger** [comment]
Hey @mjclemente - thanks for the feedback! So happy that you like it.

I'll push a fix shortly.

**Comment by mjclemente** [comment]
Thanks! 🎉
