### ISSUE TITLE
License file does not reference René Winkelmeyer

### ISSUE THREAD

**Issue by diecknet** [muenzpraeger/eleventy-chirpy-blog-template#52]
# Summary

The license file LICENSE.md references the wrong person. 

## Steps To Reproduce:

1.  Open LICENSE.md

## Expected result

License file should begin with
> MIT License
>
>  Copyright (c) 2021 René Winkelmeyer

## Actual result

License file credits "Scott Chacon and others"

> Copyright (c) 2012-2021 Scott Chacon and others

## Additional information

Awesome theme! Thanks for creating and sharing it 👍

**Comment by muenzpraeger** [comment]
Great catch! 🙏🏽 One of the rare times someone actually looks at a license file. ;-)
